name: bandart
description: Implementation of Bandit Algorithms in Dart
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  calc: ^0.2.1
  collection: ^1.17.0
  data: ^0.11.0
  statistics: ^1.0.26

dev_dependencies: 
  test: ^1.24.3
  lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

