name: bandart
description: Implementation of Bandit Algorithms in Dart
version: 0.1.0
homepage: http://dominikmeier.io

environment:
  sdk: '>=2.19.6 < 4.0.0'

dependencies:
  calc: ^0.2.1
  collection: ^1.17.0
  data: ^0.11.0
  statistics: ^1.0.26

dev_dependencies: 
  test: ^1.24.3
  lints: ^2.0.1
  build_runner: '>=2.0.0'
  mockito: '>=4.0.0'
